project_name: aloba

builds:
  - binary: aloba
    ldflags:
      - -s -w -X github.com/traefik/aloba/meta.version={{.Version}} -X github.com/traefik/aloba/meta.commit={{.Commit}} -X github.com/traefik/aloba/meta.date={{.Date}}

    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    goarm:
      - '7'

    ignore:
      - goos: darwin
        goarch: '386'
      - goos: openbsd
        goarch: arm

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^test:'
      - '^tests:'

archives:
  - id: aloba
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

docker_manifests:
  - name_template: 'traefik/aloba:{{ .Tag }}'
    image_templates:
      - 'traefik/aloba:{{ .Tag }}-amd64'
      - 'traefik/aloba:{{ .Tag }}-arm64'
  - name_template: 'traefik/aloba:latest'
    image_templates:
      - 'traefik/aloba:{{ .Tag }}-amd64'
      - 'traefik/aloba:{{ .Tag }}-arm64'
  - name_template: 'traefik/aloba:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - 'traefik/aloba:v{{ .Major }}.{{ .Minor }}-amd64'
      - 'traefik/aloba:v{{ .Major }}.{{ .Minor }}-arm64'

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: buildx.Dockerfile
    image_templates:
      - 'traefik/aloba:latest-amd64'
      - 'traefik/aloba:{{ .Tag }}-amd64'
      - 'traefik/aloba:v{{ .Major }}.{{ .Minor }}-amd64'
    build_flag_templates:
      - '--pull'
      - '--label=org.opencontainers.image.description=Add labels and milestone on pull requests and issues.'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--platform=linux/amd64'

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: buildx.Dockerfile
    image_templates:
      - 'traefik/aloba:latest-arm64'
      - 'traefik/aloba:{{ .Tag }}-arm64'
      - 'traefik/aloba:v{{ .Major }}.{{ .Minor }}-arm64'
    build_flag_templates:
      - '--pull'
      - '--label=org.opencontainers.image.description=Add labels and milestone on pull requests and issues.'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--platform=linux/arm64'
