name: "Release a tag"
on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release Process
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.19
      CGO_ENABLED: 0

    steps:

      # https://github.com/marketplace/actions/setup-go-environment
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      # https://github.com/marketplace/actions/checkout
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: dockerhub-login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ghcr-login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: traefiker
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # https://goreleaser.com/ci/actions/
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPO }}
